In [1]:
from sudoku import *

In [2]:
board = generate_board()
print('Generated Board: \n')
for i in board:
    print(i)

Generated Board: 

[1 6 4 2 8 9 5 3 7]
[7 8 9 3 6 5 1 2 4]
[5 3 2 4 1 7 6 9 8]
[2 1 3 5 4 8 7 6 9]
[4 5 6 9 7 1 2 8 3]
[8 9 7 6 3 2 4 1 5]
[3 2 1 8 5 4 9 7 6]
[6 7 5 1 9 3 8 4 2]
[9 4 8 7 2 6 3 5 1]


In [3]:
unsolved = drop_values(board, 50)
print('Unsolved Board (empty box: 60): \n')
for i in unsolved:
    print(i)

Unsolved Board (empty box: 60): 

[1 0 0 2 8 0 0 0 0]
[0 0 0 3 0 5 0 0 4]
[0 3 0 4 1 7 0 9 0]
[2 1 3 0 4 8 0 0 0]
[0 5 0 0 0 0 0 8 0]
[8 0 7 0 0 2 4 1 0]
[3 0 1 8 0 0 0 7 0]
[0 0 0 1 0 0 0 0 0]
[0 4 8 0 0 6 0 0 0]


In [4]:
solved = solver(unsolved)
print('Solved Board: \n')
for i in solved:
    print(i)

Solved
Solved Board: 

[1 6 4 2 8 9 3 5 7]
[7 8 9 3 6 5 1 2 4]
[5 3 2 4 1 7 6 9 8]
[2 1 3 5 4 8 7 6 9]
[4 5 6 9 7 1 2 8 3]
[8 9 7 6 3 2 4 1 5]
[3 2 1 8 5 4 9 7 6]
[6 7 5 1 9 3 8 4 2]
[9 4 8 7 2 6 5 3 1]


In [1]:
from sudoku import *

In [2]:
import numpy as np

In [3]:
board = np.array(
[[0,0,1,9,0,0,0,6,0],
[8,0,0,4,0,0,0,0,2],
[0,6,0,0,8,2,0,0,0],
[0,0,0,7,0,0,0,0,5],
[0,8,0,1,0,0,0,0,9],
[0,0,7,0,3,0,4,0,0],
[0,5,0,0,0,0,0,0,0],
[7,0,0,0,8,0,3,0,0],
[1,0,0,0,5,6,2,0,0]])

In [5]:
# solver(board)

In [28]:
grid =[[3, 0, 6, 5, 0, 8, 4, 0, 0], 
      [5, 2, 0, 0, 0, 0, 0, 0, 0], 
      [0, 8, 7, 0, 0, 0, 0, 3, 1], 
      [0, 0, 3, 0, 1, 0, 0, 8, 0], 
      [9, 0, 0, 8, 6, 3, 0, 0, 5], 
      [0, 5, 0, 0, 9, 0, 6, 0, 0], 
      [1, 3, 0, 0, 0, 0, 2, 5, 0], 
      [0, 0, 0, 0, 0, 0, 0, 7, 4], 
      [0, 0, 5, 2, 0, 6, 3, 0, 0]] 

In [20]:
board = np.array(
[[0,0,1,9,0,0,0,6,0],
[8,0,0,4,0,0,0,0,2],
[0,6,0,0,8,2,0,0,0],
[0,0,0,7,0,0,0,0,5],
[0,8,0,1,0,0,0,0,9],
[0,0,7,0,3,0,4,0,0],
[0,5,0,0,0,0,0,0,0],
[7,0,0,0,8,0,3,0,0],
[1,0,0,0,5,6,2,0,0]])

In [34]:
grid

[[3, 0, 6, 5, 0, 8, 4, 0, 0],
 [5, 2, 0, 0, 0, 0, 0, 0, 0],
 [0, 8, 7, 0, 0, 0, 0, 3, 1],
 [0, 0, 3, 0, 1, 0, 0, 8, 0],
 [9, 0, 0, 8, 6, 3, 0, 0, 5],
 [0, 5, 0, 0, 9, 0, 6, 0, 0],
 [1, 3, 0, 0, 0, 0, 2, 5, 0],
 [0, 0, 0, 0, 0, 0, 0, 7, 4],
 [0, 0, 5, 2, 0, 6, 3, 0, 0]]

In [37]:
solved = solver(np.array(grid))

Solved


In [39]:
for i in solved:
    print(i)

[3 1 6 5 7 8 4 9 2]
[5 2 9 1 3 4 7 6 8]
[4 8 7 6 2 9 5 3 1]
[2 6 3 4 1 5 9 8 7]
[9 7 4 8 6 3 1 2 5]
[8 5 1 7 9 2 6 4 3]
[1 3 8 9 4 7 2 5 6]
[6 9 2 3 5 1 8 7 4]
[7 4 5 2 8 6 3 1 9]
